[shell]
program="/bin/zsh"

[window]
decorations="Transparent"
opacity=0.95
startup_mode="Windowed"
dynamic_padding=true

[window.dimensions]
columns=90
lines=22

[window.position]
x=400
y=100

[window.padding]
x=5
y=25

[scrolling]
history = 100000

[font]
normal = { family = "MonoLisa Nerd Font", style = "Regular" }
bold = { family = "MonoLisa Nerd Font", style = "Bold" }
italic = { family = "MonoLisa Nerd Font", style = "Italic" }
bold_italic = { family = "MonoLisa Nerd Font", style = "Bold Italic" }
size=12
offset = { x = 1, y = 0 }

[colors.line_indicator]
foreground="#000000"
background="#ffffff"

[selection]
save_to_clipboard=true

[mouse]
hide_when_typing=true

[env]
TERM = "xterm-256color"
