[shell]
program="/bin/zsh"

[window]
decorations="None"
opacity=0.95
startup_mode="Windowed"
dynamic_padding=false

[window.dimensions]
columns=90
lines=22

[window.padding]
x=10
y=22

[scrolling]
history = 100000

[font]
size=11.5

[font.normal]
family="MonoLisa"
style="Regular"

[font.bold]
family="MonoLisa"
style="Bold"

[font.italic]
family="MonoLisa"
style="Regular Italic"

[font.bold_italic]
family="MonoLisa"
style="Bold Italic"

[colors.line_indicator]
foreground="#000000"
background="#ffffff"

[selection]
save_to_clipboard=true

[mouse]
hide_when_typing=true
